// Generated by pipeline/build_content_js.py - do not edit by hand.
export const DOTMM_LEVELS = {
 "1": {
  "name": "Dungeon Level",
  "origins": {
   "A": [
    0,
    0
   ],
   "B": [
    0,
    -43
   ],
   "C": [
    65,
    -43
   ],
   "D": [
    0,
    54
   ],
   "E": [
    54,
    25
   ],
   "F": [
    41,
    74
   ]
  },
  "packs": {
   "A": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "A",
    "grid": {
     "w": 70,
     "h": 64,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_A_BG_70x64_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "6c",
      "label": "6c",
      "name": "Uktarl's Room",
      "grid": [
       37.9,
       5.02
      ],
      "monsters": [
       {
        "name": "Bandit Captain",
        "count": 1,
        "note": "Uktarl; cowardly, retreats to 7"
       },
       {
        "name": "Bandit",
        "count": 2
       },
       {
        "name": "Doppelganger",
        "count": 1
       }
      ],
      "gm_note": "Card game with marked deck. Dwarf-mountain fresco hides a stone key (DC 13 Perception) that opens the box in 14b. Coins on the table."
     },
     {
      "id": "6a",
      "label": "6a",
      "name": "Hall of Three Lords",
      "grid": [
       46.19,
       13.98
      ],
      "monsters": [],
      "gm_note": "Rally point: if alerted, all Undertakers (captain, six bandits, two doppelgangers) gather here to extort a toll. Broken white staff wails \"Thief!\" when mended and held."
     },
     {
      "id": "6d",
      "label": "6d",
      "name": "Sleeping Quarters",
      "grid": [
       32.68,
       16.36
      ],
      "monsters": [
       {
        "name": "Bandit",
        "count": 4,
        "note": "asleep"
       },
       {
        "name": "Doppelganger",
        "count": 1,
        "note": "keeping watch"
       }
      ],
      "gm_note": "Eight bedrolls, two lanterns."
     },
     {
      "id": "5",
      "label": "5",
      "name": "Grell Hideout",
      "grid": [
       5.67,
       18.38
      ],
      "monsters": [
       {
        "name": "Grell",
        "count": 2,
        "note": "hidden in north and east alcoves; pursue fleeing prey"
       }
      ],
      "gm_note": "Black bone pillars give the grells cover. No treasure."
     },
     {
      "id": "6b",
      "label": "6b",
      "name": "Rigged Secret Door",
      "grid": [
       56.65,
       19.7
      ],
      "monsters": [],
      "gm_note": "Stacked plates crash when the door opens, alerting bandits in 6a, 6c, 6d."
     },
     {
      "id": "4",
      "label": "4",
      "name": "With Sword in Hand",
      "grid": [
       38.63,
       29.47
      ],
      "monsters": [],
      "gm_note": "Cursed glowing longsword in a stand (wielder cannot drop it). Ceiling vents carry distorted Waterdeep voices; Tiny creatures could escape through them."
     },
     {
      "id": "1",
      "label": "1",
      "name": "Entrywell",
      "grid": [
       63.99,
       30.59
      ],
      "monsters": [],
      "gm_note": "Rope drop from the Yawning Portal. A bandit watches through a secret spy-hole and retreats to warn area 6 when intruders arrive.",
      "teleport": {
       "kind": "surface",
       "label": "Up to the Yawning Portal"
      }
     },
     {
      "id": "22",
      "label": "22",
      "name": "Empty Room",
      "grid": [
       22.99,
       32.63
      ],
      "monsters": [],
      "gm_note": "Torch stubs and empty potion bottles; adventurers rest here."
     },
     {
      "id": "2a",
      "label": "2a",
      "name": "Demon Reliefs",
      "grid": [
       44.54,
       36.36
      ],
      "monsters": [],
      "gm_note": "Thirteen demon bas-reliefs. Kenku skeleton points at the nalfeshnee (secret door to 3). Dretch relief hides a second secret door to 4 with spy-hole eyes."
     },
     {
      "id": "2b",
      "label": "2b",
      "name": "Pillar Forest",
      "grid": [
       31.1,
       36.48
      ],
      "monsters": [
       {
        "name": "Bugbear",
        "count": 2,
        "note": "each hosts an intellect devourer; cannot be surprised; flee south to warn area 23"
       }
      ],
      "gm_note": "Bugbears hide behind pillars and withdraw to alert Worg\u2019s Eye. Harmless snake skeleton on north pillar; looted secret compartment in south pillar."
     },
     {
      "id": "21",
      "label": "21",
      "name": "Hall of Mirrors",
      "grid": [
       19.09,
       37.38
      ],
      "monsters": [
       {
        "name": "Shadow",
        "count": 2,
        "note": "construct duplicates; spawn when someone passes the two westernmost mirrors; vanish after 1 minute"
       }
      ],
      "gm_note": "Sixteen niche mirrors, five magical. Three illusory mirrors hide shelves; one holds the bronze Halaster mask (50 gp) \u2014 the key to area 27."
     },
     {
      "id": "23a",
      "label": "23a",
      "name": "Nimraith's Fate",
      "grid": [
       16.89,
       43.4
      ],
      "monsters": [
       {
        "name": "Goblin",
        "count": 6,
        "note": "bored, playing games"
       }
      ],
      "gm_note": "Part of Worg\u2019s Eye watch post (2 bugbears + 15 goblins total; none can be surprised if warned)."
     },
     {
      "id": "23b",
      "label": "23b",
      "name": "Shattered Statue",
      "grid": [
       24.7,
       44.63
      ],
      "monsters": [
       {
        "name": "Bugbear",
        "count": 2,
        "note": "each hosts an intellect devourer; cannot be surprised"
       }
      ],
      "gm_note": "Bugbears reassemble a statue of three warriors (17 pieces). Devourers teleport out when a host drops."
     },
     {
      "id": "3",
      "label": "3",
      "name": "Slanted Room",
      "grid": [
       45.91,
       50.14
      ],
      "monsters": [
       {
        "name": "Gray Ooze",
        "count": 1,
        "note": "psychic variant; invisible underwater north of the statue"
       }
      ],
      "gm_note": "Flooded, tilted sewer room. Sahuagin statue\u2019s screw-off head hides a wand of secrets clue; ooze psychic-crushes anyone approaching."
     },
     {
      "id": "23c",
      "label": "23c",
      "name": "Goblin Den",
      "grid": [
       17.38,
       59.16
      ],
      "monsters": [
       {
        "name": "Goblin",
        "count": 9,
        "note": "asleep unless the post is alerted"
       }
      ],
      "gm_note": "If the bugbears die, these goblins flee to 28 via 24 and 25."
     }
    ],
    "secret_doors": [
     [
      55.25,
      19.7
     ],
     [
      61.01,
      26.59
     ],
     [
      44.97,
      34.44
     ],
     [
      41.01,
      38.47
     ]
    ],
    "connectors": [
     {
      "to": "B",
      "grid": [
       44.91,
       0.99
      ]
     },
     {
      "to": "D",
      "grid": [
       10.27,
       55.49
      ]
     },
     {
      "to": "D",
      "grid": [
       32.41,
       55.49
      ]
     }
    ]
   },
   "B": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "B",
    "grid": {
     "w": 65,
     "h": 50,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_B_BG_65x50_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "14c",
      "label": "14c",
      "name": "Secret Room",
      "grid": [
       61.11,
       6.93
      ],
      "monsters": [],
      "gm_note": "Empty 10-ft room."
     },
     {
      "id": "9b",
      "label": "9b",
      "name": "Rotted Corpse",
      "grid": [
       17.57,
       8.04
      ],
      "monsters": [],
      "gm_note": "Dead Undertaker (spider venom). Intact scimitar and light crossbow; empty pouch."
     },
     {
      "id": "14a",
      "label": "14a",
      "name": "Sloping Tunnel",
      "grid": [
       47.31,
       8.95
      ],
      "monsters": [],
      "gm_note": "Empty; north tunnel slopes 20 ft down to 14b."
     },
     {
      "id": "14b",
      "label": "14b",
      "name": "Heart in a Box",
      "grid": [
       56.1,
       10.48
      ],
      "monsters": [
       {
        "name": "Sahuagin Baron",
        "count": 1,
        "note": "petrified statue; animates only if the box is pried from its grasp (DC 20 Athletics)"
       }
      ],
      "gm_note": "Floating acid dome falls (2d10/turn, floods 5 ft) if the box opens without the key from 6c. Lead-lined box holds the withered tiefling heart (swaps with the attuner\u2019s heart \u2014 instant death)."
     },
     {
      "id": "9a",
      "label": "9a",
      "name": "Pillared Way",
      "grid": [
       14.78,
       13.89
      ],
      "monsters": [],
      "gm_note": "Gem sockets looted; rusted animated-armor remains in the alcove."
     },
     {
      "id": "12",
      "label": "12",
      "name": "Hall of Heroes",
      "grid": [
       23.37,
       15.84
      ],
      "monsters": [],
      "gm_note": "Thirty-eight defaced statues; webbed ceiling; three dead giant spiders. Elder rune trap on the east double doors to 16."
     },
     {
      "id": "8c",
      "label": "8c",
      "name": "Masters of Disguise",
      "grid": [
       20.69,
       21.09
      ],
      "monsters": [
       {
        "name": "Bandit",
        "count": 5,
        "note": "disguised as vampires"
       },
       {
        "name": "Doppelganger",
        "count": 1
       }
      ],
      "gm_note": "Vampire-posing extortionists; flee to 6 when outmatched. Disguise kits and rations on the table."
     },
     {
      "id": "15",
      "label": "15",
      "name": "Armory",
      "grid": [
       57.62,
       24.19
      ],
      "monsters": [],
      "gm_note": "Collapsed weapon racks; ordinary handaxe in the south door; seized sharpening wheel in the south room."
     },
     {
      "id": "8a",
      "label": "8a",
      "name": "Hall of the Bone Throne",
      "grid": [
       28.42,
       26.34
      ],
      "monsters": [],
      "gm_note": "Wyvern remains and shattered crystal prison. Throne\u2019s serpent armrests animate and bite (poison, DC 13 Con) when someone sits or lifts the seat; hidden compartment is empty."
     },
     {
      "id": "8b",
      "label": "8b",
      "name": "Harria's Room",
      "grid": [
       19.06,
       26.84
      ],
      "monsters": [
       {
        "name": "Bandit Captain",
        "count": 1,
        "note": "Harria; sleeps unless disturbed, flees to 7"
       },
       {
        "name": "Flesh Golem",
        "count": 1,
        "note": "her guard; she cannot control it if berserk"
       }
      ],
      "gm_note": "Clown-painted trunk holds a disguise kit and costumes."
     },
     {
      "id": "13",
      "label": "13",
      "name": "Empty Room",
      "grid": [
       36.42,
       26.97
      ],
      "monsters": [],
      "gm_note": "Empty; a good spot for a regional effect of Halaster\u2019s lair."
     },
     {
      "id": "10",
      "label": "10",
      "name": "Cubicle of Skulls",
      "grid": [
       14.86,
       34.9
      ],
      "monsters": [],
      "gm_note": "Thousands of harmless skulls avalanche out when the door opens."
     },
     {
      "id": "7a",
      "label": "7a",
      "name": "Hall of Retreat",
      "grid": [
       46.35,
       36.95
      ],
      "monsters": [],
      "gm_note": "Undertakers\u2019 fallback: Uktarl and Harria make a final stand here if routed. Companion: they yield rather than die; will trade dungeon info for their lives."
     },
     {
      "id": "11",
      "label": "11",
      "name": "Room of Secrets",
      "grid": [
       21.77,
       38.0
      ],
      "monsters": [],
      "gm_note": "Wear the copper helm while sitting on the copper throne: a wand of secrets drops from the ceiling."
     },
     {
      "id": "7b",
      "label": "7b",
      "name": "Crypt",
      "grid": [
       51.25,
       43.86
      ],
      "monsters": [],
      "gm_note": "Old vampire lair, long vacant. Coffin with mist-hole holds only a vial of holy water."
     }
    ],
    "secret_doors": [
     [
      58.96,
      7.12
     ],
     [
      43.23,
      29.12
     ],
     [
      43.23,
      36.84
     ],
     [
      20.74,
      40.07
     ]
    ],
    "connectors": [
     {
      "to": "expanded",
      "grid": [
       18.37,
       3.07
      ]
     },
     {
      "to": "C",
      "grid": [
       62.42,
       16.81
      ]
     },
     {
      "to": "A",
      "grid": [
       43.77,
       45.64
      ]
     }
    ]
   },
   "C": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "C",
    "grid": {
     "w": 63,
     "h": 68,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_C_BG_63x68_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "18",
      "label": "18",
      "name": "Troll's Den",
      "grid": [
       28.07,
       8.91
      ],
      "monsters": [
       {
        "name": "Troll",
        "count": 1,
        "note": "charmed by Halaster: fetches meat daily from 19a for the manticores in 16"
       }
      ],
      "gm_note": "Putrid stench forewarns. Dispel magic (DC 15) ends the charm, not the temper."
     },
     {
      "id": "16",
      "label": "16",
      "name": "Manticore Den",
      "grid": [
       9.24,
       21.18
      ],
      "monsters": [
       {
        "name": "Manticore",
        "count": 3,
        "note": "attack all but Halaster and the charmed troll"
       }
      ],
      "gm_note": "Companion: the manticores speak Common \u2014 have them mock and goad, and remember they fly. Nest treasure includes a 250 gp bloodstone necklace. Scrying eye appears if the party returns later."
     },
     {
      "id": "20",
      "label": "20",
      "name": "Beyond the Green Door",
      "grid": [
       47.87,
       40.9
      ],
      "monsters": [],
      "gm_note": "Harmless green door with iron face. Empty room \u2014 or your hook into an expanded dungeon."
     },
     {
      "id": "17a",
      "label": "17a",
      "name": "Foyer",
      "grid": [
       9.15,
       41.49
      ],
      "monsters": [
       {
        "name": "Giant Centipede",
        "count": 2,
        "note": "inside the basilisk corpse; emerge if disturbed"
       }
      ],
      "gm_note": "Dead basilisk on its back clutches a driftglobe (pry the claw open)."
     },
     {
      "id": "19a",
      "label": "19a",
      "name": "Servants' Feast Hall",
      "grid": [
       33.07,
       42.44
      ],
      "monsters": [],
      "gm_note": "Conjured rotting meat appears on the tables at dawn; the troll from 18 feeds here daily."
     },
     {
      "id": "17b",
      "label": "17b",
      "name": "Desecrated Temple",
      "grid": [
       9.09,
       52.01
      ],
      "monsters": [
       {
        "name": "Black Pudding",
        "count": 1,
        "note": "120 hp; in stasis coating the Gond statue until touched or harmed"
       }
      ],
      "gm_note": "Eleven petrified adventurers and monsters clustered at the south end. Copper crown (75 gp) on the carrion crawler\u2019s tentacle."
     },
     {
      "id": "19b",
      "label": "19b",
      "name": "Guards' Feast Hall",
      "grid": [
       33.07,
       52.04
      ],
      "monsters": [],
      "gm_note": "Copper tankard (25 gp) under a table."
     },
     {
      "id": "19c",
      "label": "19c",
      "name": "Nobles' Feast Hall",
      "grid": [
       32.3,
       61.81
      ],
      "monsters": [],
      "gm_note": "Door blocked by a dead dwarf burglar; her nearly complete burglar\u2019s pack lies on a bench."
     }
    ],
    "secret_doors": [],
    "connectors": [
     {
      "to": "B",
      "grid": [
       1.63,
       16.29
      ]
     },
     {
      "to": "expanded",
      "grid": [
       60.81,
       39.21
      ]
     }
    ]
   },
   "D": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "D",
    "grid": {
     "w": 63,
     "h": 62,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_D_BG_63x62_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "27-demiplane",
      "label": "27",
      "name": "Hidden Demiplane (Interior)",
      "grid": [
       41.77,
       8.18
      ],
      "monsters": [
       {
        "name": "Halaster Simulacrum",
        "count": 1,
        "note": "answers three questions: first a lie, then two truths; melts afterward"
       }
      ],
      "gm_note": "Thirty-ft stone room: misty portal back, upside-down Halaster portrait. Companion: steering the party here is the level\u2019s main goal \u2014 Halaster facetime. Tossing the mask back through lets others enter.",
      "teleport": {
       "kind": "demiplane",
       "label": "Misty portal \u2192 Alcove",
       "pair": "27-alcove"
      }
     },
     {
      "id": "25a",
      "label": "25a",
      "name": "Dead Goblin",
      "grid": [
       30.26,
       8.97
      ],
      "monsters": [],
      "gm_note": "Excavation site. Goblin corpse."
     },
     {
      "id": "24a",
      "label": "24a",
      "name": "Old Gate",
      "grid": [
       10.07,
       9.2
      ],
      "monsters": [],
      "gm_note": "West tunnel exits to the expanded dungeon (or uncharted depths)."
     },
     {
      "id": "27-alcove",
      "label": "27",
      "name": "Hidden Demiplane (Alcove)",
      "grid": [
       52.51,
       12.21
      ],
      "monsters": [],
      "gm_note": "Bas-relief harpist with inscription. Stepping in while wearing the bronze mask from 21 transports you to the demiplane; anchoring objects are sheared off.",
      "teleport": {
       "kind": "demiplane",
       "label": "Mask-gate \u2192 Demiplane",
       "pair": "27-demiplane"
      }
     },
     {
      "id": "24b",
      "label": "24b",
      "name": "Dead Mage",
      "grid": [
       13.3,
       15.7
      ],
      "monsters": [],
      "gm_note": "Remains of the tiefling wizard whose withered heart waits in 14b."
     },
     {
      "id": "25b",
      "label": "25b",
      "name": "Headless Statue",
      "grid": [
       31.92,
       21.49
      ],
      "monsters": [],
      "gm_note": "Excavation site. Decapitated statue."
     },
     {
      "id": "26b",
      "label": "26b",
      "name": "Empty Closet",
      "grid": [
       16.85,
       27.22
      ],
      "monsters": [],
      "gm_note": "Empty 10-ft room."
     },
     {
      "id": "26d",
      "label": "26d",
      "name": "Mirror Gate to Level 10",
      "grid": [
       60.44,
       29.1
      ],
      "monsters": [],
      "gm_note": "Gate of the Elder Wand: touch the mirror with a charged magic wand to open for 1 minute; 11th level required; first passage triggers an elder rune. Exits at level 10 area 8.",
      "teleport": {
       "kind": "gate",
       "label": "Mirror Gate \u2192 Level 10, area 8"
      }
     },
     {
      "id": "26a",
      "label": "26a",
      "name": "Hall of Many Candles",
      "grid": [
       36.73,
       30.91
      ],
      "monsters": [],
      "gm_note": "Fifty ever-burning floating candles in 25 niches; conspicuously clean (the cube\u2019s work). Dispel magic breaks them all."
     },
     {
      "id": "26c",
      "label": "26c",
      "name": "Ooze Your Janitor?",
      "grid": [
       20.33,
       48.94
      ],
      "monsters": [
       {
        "name": "Gelatinous Cube",
        "count": 1,
        "note": "just around the corner; surprises anyone with passive Perception below 15"
       }
      ],
      "gm_note": "The cube keeps the Clean Tunnels clean."
     }
    ],
    "secret_doors": [],
    "connectors": [
     {
      "to": "A",
      "grid": [
       10.12,
       0.91
      ]
     },
     {
      "to": "A",
      "grid": [
       31.84,
       1.16
      ]
     },
     {
      "to": "expanded",
      "grid": [
       5.51,
       11.16
      ]
     },
     {
      "to": "E",
      "grid": [
       54.96,
       16.18
      ]
     }
    ]
   },
   "E": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "E",
    "grid": {
     "w": 73,
     "h": 58,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_E_BG_73x58_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "32b",
      "label": "32b",
      "name": "Bathroom",
      "grid": [
       34.99,
       5.21
      ],
      "monsters": [],
      "gm_note": "The spigot still works: hot, clean water."
     },
     {
      "id": "32a",
      "label": "32a",
      "name": "Empty Bedchamber",
      "grid": [
       44.77,
       5.92
      ],
      "monsters": [],
      "gm_note": "Cave-fresco walls; empty."
     },
     {
      "id": "30a",
      "label": "30a",
      "name": "Zigzagging Hall",
      "grid": [
       46.9,
       14.97
      ],
      "monsters": [],
      "gm_note": "Anti-archer hall. The berserk air elemental charges any opened door."
     },
     {
      "id": "33",
      "label": "33",
      "name": "North Dormitory",
      "grid": [
       67.49,
       14.97
      ],
      "monsters": [],
      "gm_note": "Eleven stone shelf-beds."
     },
     {
      "id": "29",
      "label": "29",
      "name": "Eye See You!",
      "grid": [
       20.83,
       16.87
      ],
      "monsters": [],
      "gm_note": "Sixteen heraldic shields. One of Halaster\u2019s scrying eyes studies the party, then vanishes."
     },
     {
      "id": "30b",
      "label": "30b",
      "name": "Guard Room",
      "grid": [
       55.91,
       17.76
      ],
      "monsters": [
       {
        "name": "Air Elemental",
        "count": 1,
        "note": "berserk and trapped; howls constantly; rushes any opened door"
       }
      ],
      "gm_note": "Wrecked gear on the floor. Secret door west to a tunnel connecting to 31."
     },
     {
      "id": "35",
      "label": "35",
      "name": "Hall of Rats",
      "grid": [
       40.03,
       20.42
      ],
      "monsters": [
       {
        "name": "Giant Rat",
        "count": 10
       },
       {
        "name": "Wererat",
        "count": 1,
        "note": "Flyndol Greeth, sleeping as an obese giant rat on the throne; surrenders if cornered"
       }
      ],
      "gm_note": "Two dry dwarf-face fountains in the south wall. Flyndol awaits Sylvia (31)."
     },
     {
      "id": "34",
      "label": "34",
      "name": "South Dormitory",
      "grid": [
       67.52,
       22.9
      ],
      "monsters": [],
      "gm_note": "Like 33, plus an elf skeleton with serviceable hide armor and quarterstaff."
     },
     {
      "id": "31",
      "label": "31",
      "name": "Delvers' Hall",
      "grid": [
       56.08,
       26.93
      ],
      "monsters": [
       {
        "name": "Wererat",
        "count": 1,
        "note": "Sylvia Featherstone in giant rat form; Xanathar spy hunting secret doors; flees to 35"
       }
      ],
      "gm_note": "Dwarf statues in alcoves; one pushed aside reveals the secret tunnel to 30b."
     },
     {
      "id": "28b",
      "label": "28b",
      "name": "Obelisk of the Eye",
      "grid": [
       21.03,
       31.13
      ],
      "monsters": [],
      "gm_note": "Goblin bunkroom around a 14-ft obelisk. First bare-handed touch: Halaster\u2019s telepathic riddle pointing to 38/39a and the stairs to level 2."
     },
     {
      "id": "28c",
      "label": "28c",
      "name": "East Chamber",
      "grid": [
       28.92,
       32.67
      ],
      "monsters": [
       {
        "name": "Goblin",
        "count": 6,
        "note": "jittery, bows trained on the east tunnel; ordered to kill gricks"
       }
      ],
      "gm_note": "Dead goblins and a dead grick on the floor. Secret door north (defenders unaware)."
     },
     {
      "id": "28a",
      "label": "28a",
      "name": "West Chamber",
      "grid": [
       11.76,
       34.03
      ],
      "monsters": [
       {
        "name": "Bugbear",
        "count": 2,
        "note": "standing guard"
       }
      ],
      "gm_note": "Part of Grick Snack watch post (2 bugbears + 6 goblins total)."
     },
     {
      "id": "36b",
      "label": "36b",
      "name": "Trapped Fellow",
      "grid": [
       61.86,
       35.57
      ],
      "monsters": [
       {
        "name": "Grick",
        "count": 5,
        "note": "in the diagonal hall south"
       },
       {
        "name": "Spy",
        "count": 1,
        "note": "Kelim the Weasel, sealed in the west closet; weeping; treacherous if rescued"
       }
      ],
      "gm_note": "Kelim trades a stolen spellbook (11 spells incl. lightning bolt) for rescue. Companion: he will betray anyone to save himself."
     },
     {
      "id": "36a",
      "label": "36a",
      "name": "Cricks!",
      "grid": [
       43.88,
       36.87
      ],
      "monsters": [
       {
        "name": "Grick",
        "count": 2,
        "note": "attack all who enter"
       }
      ],
      "gm_note": "Partially collapsed hall strewn with skull-crushing debris."
     },
     {
      "id": "36c",
      "label": "36c",
      "name": "Upside-Down Throne",
      "grid": [
       46.51,
       42.97
      ],
      "monsters": [
       {
        "name": "Grick Alpha",
        "count": 1,
        "note": "gorged and sleeping; ignores anyone staying 10 ft away"
       }
      ],
      "gm_note": "Permanent reverse gravity above 10 ft (dispel DC 18). Mummified minotaur on a ceiling throne has gem eyes (10 gp agate, 50 gp zircon)."
     },
     {
      "id": "28d",
      "label": "28d",
      "name": "Concealed Spiked Pit",
      "grid": [
       24.29,
       43.12
      ],
      "monsters": [],
      "gm_note": "Floor lid over a 30-ft spiked pit (3d6 + 2d10; DC 15 Perception to spot). Dead goblin below has a lucky dwarf-thumb charm."
     }
    ],
    "secret_doors": [
     [
      52.91,
      16.99
     ],
     [
      52.91,
      22.9
     ],
     [
      11.91,
      27.93
     ],
     [
      30.04,
      27.93
     ],
     [
      51.97,
      39.86
     ]
    ],
    "connectors": [
     {
      "to": "D",
      "grid": [
       1.42,
       45.25
      ]
     },
     {
      "to": "F",
      "grid": [
       11.23,
       56.96
      ]
     },
     {
      "to": "F",
      "grid": [
       19.26,
       57.17
      ]
     }
    ]
   },
   "F": {
    "schema": "dotmm-obr-pack/1",
    "level": 1,
    "map": "F",
    "grid": {
     "w": 70,
     "h": 51,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level1_F_BG_70x51_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "39d",
      "label": "39d",
      "name": "Old Forge",
      "grid": [
       50.87,
       9.05
      ],
      "monsters": [
       {
        "name": "Ettin",
        "count": 2,
        "note": "Krung-Jung and Bokk-Nokkin, Xanathar-branded"
       }
      ],
      "gm_note": "Dead forge hides sacks: 1,400 cp, 350 sp, and 120 iron ingots. Seven-thousand-pound rune-carved hammer hangs over the anvil."
     },
     {
      "id": "37",
      "label": "37",
      "name": "Map Room",
      "grid": [
       25.9,
       13.61
      ],
      "monsters": [
       {
        "name": "Revenant",
        "count": 1,
        "note": "Halleth Garke, trapped in the pit; seeks his three murderers (level 2); ally material"
       }
      ],
      "gm_note": "Wall carving of all 23 levels with three voice-buttons (Skullport / Stardock / Halaster\u2019s Tower gate access). Companion: Halleth is a self-expiring ally \u2014 use him. Secret door south to 38."
     },
     {
      "id": "39c",
      "label": "39c",
      "name": "Goblin Hall",
      "grid": [
       40.19,
       15.83
      ],
      "monsters": [
       {
        "name": "Goblin",
        "count": 19,
        "note": "starving and bickering"
       }
      ],
      "gm_note": "A twentieth goblin lies dead \u2014 an argument gone badly."
     },
     {
      "id": "40",
      "label": "40",
      "name": "Fearful Mimicry",
      "grid": [
       46.98,
       23.65
      ],
      "monsters": [
       {
        "name": "Mimic",
        "count": 1,
        "note": "Large, 75 hp; poses as the south-alcove statue with a fake gold spear"
       }
      ],
      "gm_note": "Two genuine elf-warrior statues north; rubble of the original statue behind the mimic."
     },
     {
      "id": "38",
      "label": "38",
      "name": "Secret Tunnel",
      "grid": [
       20.41,
       27.46
      ],
      "monsters": [],
      "gm_note": "Hidden curved corridor linking 37 and 39; heavy foot traffic in the dust."
     },
     {
      "id": "39b",
      "label": "39b",
      "name": "Bugbear Den",
      "grid": [
       40.16,
       34.39
      ],
      "monsters": [
       {
        "name": "Bugbear",
        "count": 3,
        "note": "one hosts an intellect devourer; cannot be surprised"
       }
      ],
      "gm_note": "Part of Big Ears watch post (3 bugbears, 19 goblins, 2 ettins; a shrieker warns them)."
     },
     {
      "id": "39a",
      "label": "39a",
      "name": "Hall of the Two-Headed King",
      "grid": [
       30.73,
       36.78
      ],
      "monsters": [],
      "gm_note": "Stairs descend 200 ft to level 2. Rotating the statue\u2019s warhammer (DC 15 Perception to notice) reveals a circlet of blasting.",
      "teleport": {
       "kind": "stairs",
       "label": "Stairs down \u2192 Level 2"
      }
     },
     {
      "id": "41",
      "label": "41",
      "name": "Cracked Ceiling",
      "grid": [
       62.39,
       39.38
      ],
      "monsters": [
       {
        "name": "Stirge",
        "count": 20,
        "note": "roost in the ceiling fissure; descend on noise or uplifted light"
       }
      ],
      "gm_note": "Mining tools in wheelbarrows. Bugbears hunt stirges here for food."
     }
    ],
    "secret_doors": [
     [
      24.92,
      18.78
     ],
     [
      21.98,
      35.28
     ]
    ],
    "connectors": [
     {
      "to": "E",
      "grid": [
       24.29,
       7.98
      ]
     },
     {
      "to": "E",
      "grid": [
       32.28,
       8.2
      ]
     },
     {
      "to": "level2",
      "grid": [
       8.89,
       39.56
      ]
     },
     {
      "to": "expanded",
      "grid": [
       54.65,
       45.27
      ]
     }
    ]
   }
  }
 },
 "2": {
  "name": "Arcane Chambers",
  "origins": {
   "A": [
    0,
    0
   ],
   "B": [
    61,
    2
   ],
   "C": [
    16,
    48
   ],
   "D": [
    0,
    62
   ],
   "E": [
    50,
    95
   ],
   "F": [
    -4,
    124
   ]
  },
  "packs": {
   "A": {
    "schema": 2,
    "level": 2,
    "map": "A",
    "grid": {
     "w": 65,
     "h": 75,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_A_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "1a",
      "label": "1a",
      "name": "",
      "grid": [
       33.27,
       39.05
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "1b",
      "label": "1b",
      "name": "",
      "grid": [
       35.55,
       13.43
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "1c",
      "label": "1c",
      "name": "",
      "grid": [
       36.77,
       19.61
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "1d",
      "label": "1d",
      "name": "",
      "grid": [
       47.02,
       26.25
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "1e",
      "label": "1e",
      "name": "",
      "grid": [
       61.16,
       34.81
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "1f",
      "label": "1f",
      "name": "",
      "grid": [
       60.3,
       15.53
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "2a",
      "label": "2a",
      "name": "",
      "grid": [
       20.96,
       46.58
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "2b",
      "label": "2b",
      "name": "",
      "grid": [
       13.12,
       51.52
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "2c",
      "label": "2c",
      "name": "",
      "grid": [
       4.83,
       55.87
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "2d",
      "label": "2d",
      "name": "",
      "grid": [
       3.27,
       49.95
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "3",
      "label": "3",
      "name": "",
      "grid": [
       8.11,
       38.07
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "4",
      "label": "4",
      "name": "",
      "grid": [
       6.07,
       23.88
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "5",
      "label": "5",
      "name": "",
      "grid": [
       8.02,
       10.39
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "6",
      "label": "6",
      "name": "",
      "grid": [
       21.56,
       37.02
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "7a",
      "label": "7a",
      "name": "",
      "grid": [
       30.12,
       53.66
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "7b",
      "label": "7b",
      "name": "",
      "grid": [
       40.92,
       50.97
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "7c",
      "label": "7c",
      "name": "",
      "grid": [
       50.6,
       55.16
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "7d",
      "label": "7d",
      "name": "",
      "grid": [
       39.82,
       67.77
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "7e",
      "label": "7e",
      "name": "",
      "grid": [
       51.91,
       68.53
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      11.99,
      15.96
     ]
    ],
    "connectors": [
     {
      "to": "expanded",
      "grid": [
       4.88,
       2.21
      ]
     },
     {
      "to": "B",
      "grid": [
       63.52,
       47.3
      ]
     },
     {
      "to": "C",
      "grid": [
       56.38,
       62.33
      ]
     }
    ],
    "traps": []
   },
   "B": {
    "schema": 2,
    "level": 2,
    "map": "B",
    "grid": {
     "w": 53,
     "h": 61,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_B_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "8",
      "label": "8",
      "name": "",
      "grid": [
       2.02,
       45.52
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "9a",
      "label": "9a",
      "name": "",
      "grid": [
       7.26,
       7.84
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "9a-2",
      "label": "9a",
      "name": "",
      "grid": [
       25.2,
       7.98
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "9b",
      "label": "9b",
      "name": "",
      "grid": [
       23.23,
       15.0
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "9c",
      "label": "9c",
      "name": "",
      "grid": [
       7.93,
       16.53
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "9d",
      "label": "9d",
      "name": "",
      "grid": [
       8.0,
       27.31
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "10a",
      "label": "10a",
      "name": "",
      "grid": [
       25.39,
       31.14
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "10b",
      "label": "10b",
      "name": "",
      "grid": [
       16.04,
       27.77
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "10c",
      "label": "10c",
      "name": "",
      "grid": [
       16.07,
       37.36
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "10d",
      "label": "10d",
      "name": "",
      "grid": [
       23.84,
       39.71
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "11a",
      "label": "11a",
      "name": "",
      "grid": [
       37.05,
       46.87
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "11b",
      "label": "11b",
      "name": "",
      "grid": [
       49.13,
       38.54
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "12",
      "label": "12",
      "name": "",
      "grid": [
       13.92,
       50.78
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      46.06,
      9.53
     ]
    ],
    "connectors": [
     {
      "to": "expanded",
      "grid": [
       3.68,
       4.33
      ]
     },
     {
      "to": "expanded",
      "grid": [
       51.04,
       27.39
      ]
     },
     {
      "to": "A",
      "grid": [
       1.33,
       47.45
      ]
     },
     {
      "to": "C",
      "grid": [
       49.45,
       60.2
      ]
     }
    ],
    "traps": [
     [
      4.01,
      8.04
     ],
     [
      9.99,
      8.04
     ],
     [
      15.99,
      8.04
     ],
     [
      22.04,
      8.04
     ],
     [
      28.04,
      8.04
     ]
    ]
   },
   "C": {
    "schema": 2,
    "level": 2,
    "map": "C",
    "grid": {
     "w": 98,
     "h": 51,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_C_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "13a",
      "label": "13a",
      "name": "",
      "grid": [
       41.17,
       12.36
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13b",
      "label": "13b",
      "name": "",
      "grid": [
       37.77,
       38.35
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13c",
      "label": "13c",
      "name": "",
      "grid": [
       30.18,
       35.97
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13d",
      "label": "13d",
      "name": "",
      "grid": [
       30.18,
       47.7
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13e",
      "label": "13e",
      "name": "",
      "grid": [
       22.18,
       42.51
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13f",
      "label": "13f",
      "name": "",
      "grid": [
       85.29,
       20.73
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "13g",
      "label": "13g",
      "name": "",
      "grid": [
       57.69,
       34.12
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "14a",
      "label": "14a",
      "name": "",
      "grid": [
       7.42,
       39.12
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "14b",
      "label": "14b",
      "name": "",
      "grid": [
       9.08,
       46.54
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "15",
      "label": "15",
      "name": "",
      "grid": [
       9.18,
       30.68
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "16",
      "label": "16",
      "name": "",
      "grid": [
       19.96,
       30.8
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      9.46,
      22.65
     ]
    ],
    "connectors": [
     {
      "to": "A",
      "grid": [
       37.27,
       11.87
      ]
     },
     {
      "to": "B",
      "grid": [
       94.47,
       12.06
      ]
     },
     {
      "to": "E",
      "grid": [
       78.2,
       45.26
      ]
     },
     {
      "to": "E",
      "grid": [
       82.31,
       45.27
      ]
     },
     {
      "to": "expanded",
      "grid": [
       96.2,
       45.38
      ]
     },
     {
      "to": "D",
      "grid": [
       16.5,
       50.28
      ]
     }
    ],
    "traps": []
   },
   "D": {
    "schema": 2,
    "level": 2,
    "map": "D",
    "grid": {
     "w": 57,
     "h": 64,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_D_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "17",
      "label": "17",
      "name": "",
      "grid": [
       25.39,
       40.92
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "18",
      "label": "18",
      "name": "",
      "grid": [
       12.12,
       11.92
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "19a",
      "label": "19a",
      "name": "",
      "grid": [
       6.04,
       44.7
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "19b",
      "label": "19b",
      "name": "",
      "grid": [
       5.65,
       54.08
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "19c",
      "label": "19c",
      "name": "",
      "grid": [
       7.25,
       36.1
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "19d",
      "label": "19d",
      "name": "",
      "grid": [
       4.1,
       12.46
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "19e",
      "label": "19e",
      "name": "",
      "grid": [
       4.96,
       24.1
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22a",
      "label": "22a",
      "name": "",
      "grid": [
       52.79,
       53.37
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22b",
      "label": "22b",
      "name": "",
      "grid": [
       49.12,
       52.79
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22c",
      "label": "22c",
      "name": "",
      "grid": [
       40.38,
       52.93
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22d",
      "label": "22d",
      "name": "",
      "grid": [
       26.98,
       52.91
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22e",
      "label": "22e",
      "name": "",
      "grid": [
       14.25,
       48.02
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "22f",
      "label": "22f",
      "name": "",
      "grid": [
       14.09,
       58.14
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      17.02,
      51.98
     ],
     [
      17.02,
      53.91
     ]
    ],
    "connectors": [
     {
      "to": "expanded",
      "grid": [
       1.86,
       19.29
      ]
     },
     {
      "to": "C",
      "grid": [
       34.31,
       36.7
      ]
     },
     {
      "to": "E",
      "grid": [
       52.7,
       39.28
      ]
     },
     {
      "to": "E",
      "grid": [
       55.63,
       56.66
      ]
     }
    ],
    "traps": [
     [
      20.98,
      53.03
     ],
     [
      25.0,
      53.03
     ],
     [
      29.01,
      53.03
     ]
    ]
   },
   "E": {
    "schema": 2,
    "level": 2,
    "map": "E",
    "grid": {
     "w": 64,
     "h": 69,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_E_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "20a",
      "label": "20a",
      "name": "",
      "grid": [
       41.41,
       11.84
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "20b",
      "label": "20b",
      "name": "",
      "grid": [
       33.2,
       12.97
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "20c",
      "label": "20c",
      "name": "",
      "grid": [
       28.0,
       8.01
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "20d",
      "label": "20d",
      "name": "",
      "grid": [
       18.53,
       17.0
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "21",
      "label": "21",
      "name": "",
      "grid": [
       21.23,
       22.89
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "23a",
      "label": "23a",
      "name": "",
      "grid": [
       22.09,
       39.08
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25a",
      "label": "25a",
      "name": "",
      "grid": [
       11.0,
       50.1
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25b",
      "label": "25b",
      "name": "",
      "grid": [
       22.11,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25c",
      "label": "25c",
      "name": "",
      "grid": [
       27.98,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25d",
      "label": "25d",
      "name": "",
      "grid": [
       33.99,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25e",
      "label": "25e",
      "name": "",
      "grid": [
       39.93,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25f",
      "label": "25f",
      "name": "",
      "grid": [
       47.06,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25g",
      "label": "25g",
      "name": "",
      "grid": [
       55.01,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25h",
      "label": "25h",
      "name": "",
      "grid": [
       61.02,
       43.82
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25i",
      "label": "25i",
      "name": "",
      "grid": [
       23.03,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25j",
      "label": "25j",
      "name": "",
      "grid": [
       27.0,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25k",
      "label": "25k",
      "name": "",
      "grid": [
       31.04,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25l",
      "label": "25l",
      "name": "",
      "grid": [
       35.03,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25m",
      "label": "25m",
      "name": "",
      "grid": [
       38.94,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25n",
      "label": "25n",
      "name": "",
      "grid": [
       43.15,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25o",
      "label": "25o",
      "name": "",
      "grid": [
       47.05,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25p",
      "label": "25p",
      "name": "",
      "grid": [
       51.01,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25q",
      "label": "25q",
      "name": "",
      "grid": [
       54.92,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "25r",
      "label": "25r",
      "name": "",
      "grid": [
       59.0,
       55.49
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      29.98,
      12.05
     ],
     [
      26.86,
      14.94
     ],
     [
      60.9,
      49.02
     ]
    ],
    "connectors": [
     {
      "to": "C",
      "grid": [
       44.15,
       0.78
      ]
     },
     {
      "to": "C",
      "grid": [
       48.19,
       0.78
      ]
     },
     {
      "to": "D",
      "grid": [
       1.41,
       6.29
      ]
     },
     {
      "to": "D",
      "grid": [
       1.44,
       23.32
      ]
     },
     {
      "to": "level3",
      "grid": [
       58.52,
       35.91
      ]
     },
     {
      "to": "F",
      "grid": [
       1.58,
       39.2
      ]
     },
     {
      "to": "F",
      "grid": [
       1.42,
       50.4
      ]
     },
     {
      "to": "expanded",
      "grid": [
       40.71,
       58.11
      ]
     }
    ],
    "traps": []
   },
   "F": {
    "schema": 2,
    "level": 2,
    "map": "F",
    "grid": {
     "w": 57,
     "h": 38,
     "pixels_per_grid": 100
    },
    "dd2vtt_file": "Level2_F_*_FVTT.dd2vtt",
    "rooms": [
     {
      "id": "23b",
      "label": "23b",
      "name": "",
      "grid": [
       36.69,
       7.7
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "24",
      "label": "24",
      "name": "",
      "grid": [
       8.24,
       12.03
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "26a",
      "label": "26a",
      "name": "",
      "grid": [
       50.52,
       26.95
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "26b",
      "label": "26b",
      "name": "",
      "grid": [
       47.4,
       15.9
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "26c",
      "label": "26c",
      "name": "",
      "grid": [
       37.55,
       27.71
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "26d",
      "label": "26d",
      "name": "",
      "grid": [
       22.09,
       19.75
      ],
      "monsters": [],
      "gm_note": ""
     },
     {
      "id": "26e",
      "label": "26e",
      "name": "",
      "grid": [
       8.35,
       18.8
      ],
      "monsters": [],
      "gm_note": ""
     }
    ],
    "secret_doors": [
     [
      49.17,
      17.98
     ]
    ],
    "connectors": [
     {
      "to": "E",
      "grid": [
       55.6,
       8.54
      ]
     },
     {
      "to": "E",
      "grid": [
       55.62,
       19.88
      ]
     },
     {
      "to": "expanded",
      "grid": [
       3.98,
       21.32
      ]
     }
    ],
    "traps": []
   }
  }
 }
};

export const TOKEN_MANIFEST = {
 "note": "Provide one image per monster name. Accepted filename forms (case-insensitive): exact name with spaces, hyphens, or underscores, e.g. \"Bandit Captain.png\", \"bandit-captain.webp\", \"bandit_captain.jpg\".",
 "monsters": [
  {
   "name": "Air Elemental",
   "total": 1,
   "rooms": [
    "E:30b"
   ]
  },
  {
   "name": "Bandit",
   "total": 11,
   "rooms": [
    "A:6c",
    "A:6d",
    "B:8c"
   ]
  },
  {
   "name": "Bandit Captain",
   "total": 2,
   "rooms": [
    "A:6c",
    "B:8b"
   ]
  },
  {
   "name": "Black Pudding",
   "total": 1,
   "rooms": [
    "C:17b"
   ]
  },
  {
   "name": "Bugbear",
   "total": 9,
   "rooms": [
    "A:2b",
    "A:23b",
    "E:28a",
    "F:39b"
   ]
  },
  {
   "name": "Doppelganger",
   "total": 3,
   "rooms": [
    "A:6c",
    "A:6d",
    "B:8c"
   ]
  },
  {
   "name": "Ettin",
   "total": 2,
   "rooms": [
    "F:39d"
   ]
  },
  {
   "name": "Flesh Golem",
   "total": 1,
   "rooms": [
    "B:8b"
   ]
  },
  {
   "name": "Gelatinous Cube",
   "total": 1,
   "rooms": [
    "D:26c"
   ]
  },
  {
   "name": "Giant Centipede",
   "total": 2,
   "rooms": [
    "C:17a"
   ]
  },
  {
   "name": "Giant Rat",
   "total": 10,
   "rooms": [
    "E:35"
   ]
  },
  {
   "name": "Goblin",
   "total": 40,
   "rooms": [
    "A:23a",
    "A:23c",
    "E:28c",
    "F:39c"
   ]
  },
  {
   "name": "Gray Ooze",
   "total": 1,
   "rooms": [
    "A:3"
   ]
  },
  {
   "name": "Grell",
   "total": 2,
   "rooms": [
    "A:5"
   ]
  },
  {
   "name": "Grick",
   "total": 7,
   "rooms": [
    "E:36b",
    "E:36a"
   ]
  },
  {
   "name": "Grick Alpha",
   "total": 1,
   "rooms": [
    "E:36c"
   ]
  },
  {
   "name": "Halaster Simulacrum",
   "total": 1,
   "rooms": [
    "D:27-demiplane"
   ]
  },
  {
   "name": "Manticore",
   "total": 3,
   "rooms": [
    "C:16"
   ]
  },
  {
   "name": "Mimic",
   "total": 1,
   "rooms": [
    "F:40"
   ]
  },
  {
   "name": "Revenant",
   "total": 1,
   "rooms": [
    "F:37"
   ]
  },
  {
   "name": "Sahuagin Baron",
   "total": 1,
   "rooms": [
    "B:14b"
   ]
  },
  {
   "name": "Shadow",
   "total": 2,
   "rooms": [
    "A:21"
   ]
  },
  {
   "name": "Spy",
   "total": 1,
   "rooms": [
    "E:36b"
   ]
  },
  {
   "name": "Stirge",
   "total": 20,
   "rooms": [
    "F:41"
   ]
  },
  {
   "name": "Troll",
   "total": 1,
   "rooms": [
    "C:18"
   ]
  },
  {
   "name": "Wererat",
   "total": 2,
   "rooms": [
    "E:35",
    "E:31"
   ]
  }
 ]
};
