// Generated by the DotMM content pipeline - do not edit by hand.
export const TOKEN_MANIFEST = {
 "note": "Provide one image per monster name. Accepted filename forms (case-insensitive): exact name with spaces, hyphens, or underscores, e.g. \"Bandit Captain.png\", \"bandit-captain.webp\", \"bandit_captain.jpg\".",
 "monsters": [
  {
   "name": "Air Elemental",
   "total": 1,
   "rooms": [
    "E:30b"
   ]
  },
  {
   "name": "Allip",
   "total": 1,
   "rooms": [
    "A:2d"
   ]
  },
  {
   "name": "Animated Armor",
   "total": 1,
   "rooms": [
    "A:3"
   ]
  },
  {
   "name": "Animated Object",
   "total": 2,
   "rooms": [
    "E:21"
   ]
  },
  {
   "name": "Badger",
   "total": 1,
   "rooms": [
    "E:25p"
   ]
  },
  {
   "name": "Bandit",
   "total": 11,
   "rooms": [
    "A:6c",
    "A:6d",
    "B:8c"
   ]
  },
  {
   "name": "Bandit Captain",
   "total": 2,
   "rooms": [
    "A:6c",
    "B:8b"
   ]
  },
  {
   "name": "Beholder Zombie",
   "total": 2,
   "rooms": [
    "D:22c",
    "E:20a"
   ]
  },
  {
   "name": "Berserker",
   "total": 1,
   "rooms": [
    "E:20b"
   ]
  },
  {
   "name": "Black Pudding",
   "total": 1,
   "rooms": [
    "C:17b"
   ]
  },
  {
   "name": "Boar",
   "total": 1,
   "rooms": [
    "E:25i"
   ]
  },
  {
   "name": "Bugbear",
   "total": 33,
   "rooms": [
    "A:2b",
    "A:23b",
    "E:28a",
    "F:39b",
    "A:1e",
    "B:9a",
    "B:9d",
    "E:20b",
    "E:20d"
   ]
  },
  {
   "name": "Bullywug",
   "total": 4,
   "rooms": [
    "E:25b"
   ]
  },
  {
   "name": "Constrictor Snake",
   "total": 1,
   "rooms": [
    "E:25j"
   ]
  },
  {
   "name": "Doppelganger",
   "total": 3,
   "rooms": [
    "A:6c",
    "A:6d",
    "B:8c"
   ]
  },
  {
   "name": "Drow",
   "total": 2,
   "rooms": [
    "E:25d"
   ]
  },
  {
   "name": "Drow Elite Warrior",
   "total": 1,
   "rooms": [
    "B:9b"
   ]
  },
  {
   "name": "Drow Mage",
   "total": 1,
   "rooms": [
    "C:14a"
   ]
  },
  {
   "name": "Ettin",
   "total": 2,
   "rooms": [
    "F:39d"
   ]
  },
  {
   "name": "Flameskull",
   "total": 1,
   "rooms": [
    "A:7c"
   ]
  },
  {
   "name": "Flesh Golem",
   "total": 2,
   "rooms": [
    "B:8b",
    "A:7c"
   ]
  },
  {
   "name": "Gelatinous Cube",
   "total": 2,
   "rooms": [
    "D:26c",
    "B:10a"
   ]
  },
  {
   "name": "Ghast",
   "total": 3,
   "rooms": [
    "A:7d"
   ]
  },
  {
   "name": "Ghoul",
   "total": 6,
   "rooms": [
    "A:7b"
   ]
  },
  {
   "name": "Giant Centipede",
   "total": 2,
   "rooms": [
    "C:17a"
   ]
  },
  {
   "name": "Giant Rat",
   "total": 10,
   "rooms": [
    "E:35"
   ]
  },
  {
   "name": "Giant Spider",
   "total": 5,
   "rooms": [
    "D:19d"
   ]
  },
  {
   "name": "Gibbering Mouther",
   "total": 4,
   "rooms": [
    "C:13a",
    "C:13f"
   ]
  },
  {
   "name": "Goat",
   "total": 6,
   "rooms": [
    "E:25g"
   ]
  },
  {
   "name": "Goblin",
   "total": 80,
   "rooms": [
    "A:23a",
    "A:23c",
    "E:28c",
    "F:39c",
    "A:1b",
    "A:1c",
    "A:1d",
    "A:1d",
    "A:1e"
   ]
  },
  {
   "name": "Goblin Boss",
   "total": 1,
   "rooms": [
    "A:1e"
   ]
  },
  {
   "name": "Gray Ooze",
   "total": 1,
   "rooms": [
    "A:3"
   ]
  },
  {
   "name": "Grell",
   "total": 2,
   "rooms": [
    "A:5"
   ]
  },
  {
   "name": "Grick",
   "total": 10,
   "rooms": [
    "E:36b",
    "E:36a",
    "E:25c"
   ]
  },
  {
   "name": "Grick Alpha",
   "total": 1,
   "rooms": [
    "E:36c"
   ]
  },
  {
   "name": "Halaster Blackcloak",
   "total": 1,
   "rooms": [
    "E:25h"
   ]
  },
  {
   "name": "Halaster Simulacrum",
   "total": 1,
   "rooms": [
    "D:27-demiplane"
   ]
  },
  {
   "name": "Human Thug",
   "total": 5,
   "rooms": [
    "E:20b"
   ]
  },
  {
   "name": "Human Wererat",
   "total": 1,
   "rooms": [
    "E:25r"
   ]
  },
  {
   "name": "Intellect Devourer",
   "total": 2,
   "rooms": [
    "B:9b"
   ]
  },
  {
   "name": "Kenku",
   "total": 1,
   "rooms": [
    "E:25k"
   ]
  },
  {
   "name": "Lizardfolk",
   "total": 1,
   "rooms": [
    "E:25l"
   ]
  },
  {
   "name": "Manticore",
   "total": 3,
   "rooms": [
    "C:16"
   ]
  },
  {
   "name": "Mezzoloth",
   "total": 1,
   "rooms": [
    "C:13g"
   ]
  },
  {
   "name": "Mimic",
   "total": 4,
   "rooms": [
    "F:40",
    "D:22f"
   ]
  },
  {
   "name": "Mind Flayer",
   "total": 1,
   "rooms": [
    "E:25m"
   ]
  },
  {
   "name": "Modron",
   "total": 1,
   "rooms": [
    "E:25a"
   ]
  },
  {
   "name": "Nothic",
   "total": 7,
   "rooms": [
    "C:13e",
    "C:13g",
    "E:25n"
   ]
  },
  {
   "name": "Ochre Jelly",
   "total": 1,
   "rooms": [
    "B:10c"
   ]
  },
  {
   "name": "Orc War Chief",
   "total": 1,
   "rooms": [
    "E:25o"
   ]
  },
  {
   "name": "Owlbear",
   "total": 2,
   "rooms": [
    "F:26a"
   ]
  },
  {
   "name": "Priest",
   "total": 1,
   "rooms": [
    "B:11b"
   ]
  },
  {
   "name": "Quaggoth",
   "total": 1,
   "rooms": [
    "E:25q"
   ]
  },
  {
   "name": "Revenant",
   "total": 1,
   "rooms": [
    "F:37"
   ]
  },
  {
   "name": "Rust Monster",
   "total": 6,
   "rooms": [
    "D:17",
    "E:25e"
   ]
  },
  {
   "name": "Sahuagin Baron",
   "total": 1,
   "rooms": [
    "B:14b"
   ]
  },
  {
   "name": "Shadow",
   "total": 2,
   "rooms": [
    "A:21"
   ]
  },
  {
   "name": "Skeleton",
   "total": 9,
   "rooms": [
    "D:22a"
   ]
  },
  {
   "name": "Specter",
   "total": 1,
   "rooms": [
    "A:2c"
   ]
  },
  {
   "name": "Spy",
   "total": 1,
   "rooms": [
    "E:36b"
   ]
  },
  {
   "name": "Stirge",
   "total": 20,
   "rooms": [
    "F:41"
   ]
  },
  {
   "name": "Swarm of Spiders",
   "total": 1,
   "rooms": [
    "D:19e"
   ]
  },
  {
   "name": "Troglodyte",
   "total": 5,
   "rooms": [
    "E:25f"
   ]
  },
  {
   "name": "Troll",
   "total": 1,
   "rooms": [
    "C:18"
   ]
  },
  {
   "name": "Unseen Servant",
   "total": 9,
   "rooms": [
    "B:11b"
   ]
  },
  {
   "name": "Wererat",
   "total": 10,
   "rooms": [
    "E:35",
    "E:31",
    "C:14b"
   ]
  },
  {
   "name": "Xanathar Guild Thug",
   "total": 7,
   "rooms": [
    "B:9b"
   ]
  }
 ]
};
