"""Bundle all level packs + token manifest into content.js (repo root).

Reads packs/content_A..F.json (Level 1) and packs/content_L2_*.json
(Level 2), attaches per-level origins and display names, and emits the
DOTMM_LEVELS structure the importer consumes. Rerun after editing packs:

    python3 pipeline/build_content_js.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LEVELS = {
    "1": {
        "name": "Dungeon Level",
        "packfile": "content_{L}.json",
        # Field-confirmed origins (B/C corrections baked 2026-07-07).
        "origins": {"A": [0, 0], "B": [0, -43], "C": [65, -43],
                    "D": [0, 54], "E": [54, 25], "F": [41, 74]},
    },
    "2": {
        "name": "Arcane Chambers",
        "packfile": "content_L2_{L}.json",
        # Registered against the TYCH map key; F pinned by E<->F connectors.
        "origins": {"A": [0, 0], "B": [61, 2], "C": [16, 48],
                    "D": [0, 62], "E": [50, 95], "F": [-4, 124]},
    },
}

out_levels = {}
for level, meta in LEVELS.items():
    packs = {}
    for L in "ABCDEF":
        path = os.path.join(ROOT, "packs", meta["packfile"].format(L=L))
        if not os.path.exists(path):
            continue
        packs[L] = json.load(open(path))
    out_levels[level] = {
        "name": meta["name"],
        "origins": {k: v for k, v in meta["origins"].items() if k in packs},
        "packs": packs,
    }

manifest = json.load(open(os.path.join(ROOT, "packs", "token_manifest.json")))

out = (
    "// Generated by pipeline/build_content_js.py - do not edit by hand.\n"
    "export const DOTMM_LEVELS = " + json.dumps(out_levels, indent=1) + ";\n\n"
    "export const TOKEN_MANIFEST = " + json.dumps(manifest, indent=1) + ";\n"
)
with open(os.path.join(ROOT, "content.js"), "w") as f:
    f.write(out)
for level, data in out_levels.items():
    rooms = sum(len(p["rooms"]) for p in data["packs"].values())
    print(f"level {level} ({data['name']}): {len(data['packs'])} maps, {rooms} rooms")
print("wrote content.js")
